### ISSUE TITLE
Dokumentacja

### ISSUE THREAD

**Issue by andrzejwp** [szymon-planeta/209369#1]
Proszę używać docbloków opisujących poszczególne metody, powinny zawierać opis danej metody i jej interfejsu, aby ułatwić innym korzystanie z metody.

**Comment by szymon-planeta** [comment]
Czy chodzi o to, żeby docbloki umieszczać również w plikach cpp? Czy o to, że komentarze opisujące metody, które zamieściłem w plikach nagłówkowych są za mało rozbudowane?

**Comment by andrzejwp** [comment]
ma pan racje, nie bylo tematu, moj blad
